### ISSUE TITLE
Add the size of the statusList as a property

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-looker-oauth-jwt-cwt-status-list#5]
It could be handy to include the size of the statusList, i.e. the total number of entities and there status.
This could serve as an additional check that the statusList was correctly uncompressed and decoded by the verifier, especially if we think about including variable size of bits per status, see #1 
Proposed change to the current draft:
```
{
  "alg": "ES256",
  "kid": "11"
}
.
{
  "iss": "https://example.com",
  "iat": 1683560915,
  "exp": 1686232115,
  "sts_lst": {
    "typ": "revocation-list",
    "size": 16384,
    "lst": "H4sIAAAAAAAAA-3BMQEAAADCoPVPbQwfoAA......IC3AYbSVKsAQAAA"
  }
}
```

**Comment by tplooker** [comment]
Just so I understand better @paulbastian is your concern that developers would struggle to decode the status list reliably and that size would assist in validating this was done correctly? Because if so I think test vectors would probably assist in this regard. If its about corruption of the list it self I dont think that is of material concern because the list is always signed. R.e multi bits per status what would size convey in this context the number of bits/bytes or statuses represented?

**Comment by paulbastian** [comment]
Exactly, integrity is protected by the signature, but uncompressing and getting the correct index needs to be done correctly. I agree we should add text vectors to the spec, let's open an issue on that

**Comment by paulbastian** [comment]
@tplooker are you arguing that it is not necessary at all? While I agree that you could get additional safety of correct deciding through test vectors, I think it is anyway a useful metadata to have and does not take large amounts of space.

**Comment by paulbastian** [comment]
Agreed to not integrate this
